server.port=8085

feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000

# URL de los microservicios
ms.pacientes.url=http://localhost:8081
ms.citas.url=http://localhost:8082

# Configuración de logging
logging.level.root=INFO
logging.level.cl.duoc.rednorte=DEBUG

# Otras configuraciones necesarias
spring.application.name=bff-rednorte
spring.cloud.openfeign.enabled=true
